version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: todo_list
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://usuario:senha@db/todo_list
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
